version: '3'
services:
  mongodb:
    container_name: juice-mongodb
    image: mongo:7.0.4
    restart: on-failure:3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - kind
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    container_name: juice-mongo-express
    image: mongo-express
    restart: on-failure:3
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    networks:
      - kind
    ports:
      - 8081:8081

networks:
  kind:
    external: true